language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - python setup.py install
script:
  - python setup.py test
after_success:
  - coverage run --source=trilpy setup.py test
  - coveralls
