language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - python setup.py install
script:
  - python setup.py test
  - python prezi2to3.py tests/input_data/manifest-basic.json --output /dev/null
after_success:
  - coverage run --source=iiif_prezi_upgrader setup.py test
  - coveralls
